config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :site do
    get 'home', to: 'home#index'
  end
  namespace :backoffice do
    resources :categories, except: %i[show destroy]
    resources :admins, except: %i[show]
    resources :send_mail, only: %i[edit create]
    get 'dashboard', to: 'dashboard#index'
  end

  devise_for :admins, skip: [:registrations]
  devise_for :members

  root 'site/home#index'
  get 'backoffice', to: 'backoffice/dashboard#index'
end

app/models/ad.rb
# frozen_string_literal: true

class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  ROLES = { full_access: 0, restricted_access: 1 }.freeze

  enum role: ROLES

  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates_presence_of :description
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Class main of the controller
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      'backoffice_devise'
    else
      'application'
    end
  end

  def user_not_authorized
    flash[:alert] = 'Você não está autorizado a executar essa ação.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/backoffice/admins_controller.rb
# frozen_string_literal: true

# Main Backoffice
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: %i[edit update destroy]
  after_action :verify_authorized, only: :new
  after_action :verify_policy_scoped, only: :index

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path,
                  notice: "Sucesso ao criar: Administrador (#{@admin.email})!"
    else
      render :new
    end
  end

  def edit; end

  def update
    if params_admin.values_at(:password, :password_confirmation).all?(&:blank?)
      admin_params = params_admin.except(%i[password password_confirmation])
    else
      admin_params = params_admin
    end

    if @admin.update(admin_params)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path,
                  notice: "Sucesso ao alterar: Administrador (#{@admin.email})!"
    else
      p @admin.errors.full_messages
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path,
                  notice: "Sucesso ao excluír: Administrador (#{admin_email})!"
    else
      render :index
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(
      :email, :name, :role, :password, :password_confirmation
    )
  end
end

app/controllers/backoffice/categories_controller.rb
# frozen_string_literal: true

class Backoffice::CategoriesController < BackofficeController
  # before_action :set_category, only: [:edit, :update]
  before_action :set_category, only: %i[edit update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = CategoryService.create(params_category)

    if @category.errors.any?
      render 'new'
    else
      redirect_to backoffice_categories_path,
                  notice: "Sucesso ao Criar: Categoria (#{@category.description})!"
    end
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path,
                  notice: "Sucesso ao Alterar: Categoria (#{@category.description})!"
    else
      render 'edit'
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/categories_controller/category_service.rb
# frozen_string_literal: true

class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    @category.save! if @category.valid?

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
# frozen_string_literal: true

class Backoffice::DashboardController < BackofficeController
  def index; end
end

app/controllers/backoffice/send_mail_controller.rb
# frozen_string_literal: true

# Class SendMail
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_email(
        current_admin,
        params[:'recipient-text'],
        params[:'subject-text'],
        params[:'message-text']
      ).deliver_now
      @notify_message = 'E-mail enviado com sucesso!'
      @notify_flag = 'success'
    rescue StandardError
      @notify_message = 'Erro ao enviar o e-mail.'
      @notify_flag = 'error'
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
# frozen_string_literal: true

class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'backoffice'

  def pundit_user
    current_admin
  end
end

app/controllers/site/home_controller.rb
# frozen_string_literal: true

class Site::HomeController < ApplicationController
  layout 'site'

  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
# frozen_string_literal: true

module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
# frozen_string_literal: true

module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
# frozen_string_literal: true

module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
# frozen_string_literal: true

module Backoffice::SendMailHelper
end

app/helpers/site/home_helper.rb
# frozen_string_literal: true

module Site::HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/backoffice/admins/_form.html.erb
<h1 class="page-header">Administrador</h1>
<div class="col-lg-12">
  <% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

      <div id="error_explanation">
        <ul>
          <% @admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= action %>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-6">
          <%= form_for ([:backoffice, @admin]) do |f| %>
            <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:"form-control", placeholder:"Ex.: Nome do Administrador" %>
            </div>
            <div class="form-group">
              <label>E-mail</label>
              <%= f.text_field :email, class:"form-control", placeholder:"Ex.: seu_nome@email.com" %>
            </div>
            <% if policy(@admin).edit? %>
              <div class="form-group">
                <label>Tipo de Acesso</label>
                <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                  <div class="radio">
                      <%= b.label { b.radio_button + b.text } %>
                  </div>  
                <% end %>
              </div>
            <% end %>
            <div class="form-group">
              <label>Senha</label>
              <%= f.password_field :password, class:"form-control", placeholder:"Ex.: Senha" %>
            </div>
            <div class="form-group">
              <label>Confirmar Senha</label>
              <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Ex.: Confirmar Senha" %>
            </div>
              <%= f.submit "Enviar", class:"btn btn-primary" %>
              <%= link_to "Voltar", backoffice_admins_path, class:"btn btn-default" %>
          <% end %>
        </div>
        <!-- /.col-lg-6 (nested) -->
      </div>
      <!-- /.row (nested) -->
    </div>
    <!-- /.panel-body -->
  </div>
</div>

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'form', locals: {action: 'Editando Administrador'} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administrador</h1>

<div class="col-lg-12">
	<div class="panel panel-default" >
		<div class="panel-heading" >
			Listando Administradores
			<% if policy(@admins).new? %>
				<%= link_to new_backoffice_admin_path, 
						class:"btn btn-success btn-circle navbar-right", style:"margin:-5px -5px 0 0" do %>
						<i class="fa fa-plus"></i>
				<% end %>
			<% else %>
				<button class="btn btn-success btn-circle navbar-right" style="margin:-5px -5px 0 0" disabled="disabled">
					<i class="fa fa-plus"></i>
				</button>
			<% end %>
		</div>
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive" >
				<table class="table table-striped table-bordered table-hover" >
					<thead>
						<tr>
							<th>Id</th>
							<th>Nome</th>
							<th>Tipo de Acesso</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @admins.each do |admin| %>
							<tr>
								<td><%= admin.id %></td>
								<td><%= admin.name %></td>
								<td><%= admin.role_i18n %></td>
								<td>
									<%= link_to edit_backoffice_send_mail_path(admin), class:"btn btn-info btn-circle", remote: true do %>
										<i class="fa fa-envelope"></i>
									<%  end %>
									<%= link_to edit_backoffice_admin_path(admin), class:"btn btn-primary btn-circle" do %> 
										<i class="fa fa-edit"></i>
									<%  end %>
									<% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
										<%= link_to backoffice_admin_path(admin),
																data: {confirm: t('messages.confirm_with', item: admin.name)},
																method: :delete,
																class:'btn btn-danger btn-circle' do %>
											<i class="fa fa-minus"></i>										
										<% end %>
									<% else %>
										<button class="btn btn-danger btn-circle" disabled="disabled">
											<i class="fa fa-minus"></i>
										</button>
									<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- /.panel -->
</div>

<%= render partial: 'backoffice/admins/shared/send_mail_modal' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: 'form', locals: {action: 'Novo Administrador'} %>

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <%= text_field_tag(:'recipient-text', nil, class:"form-control", readonly:'readonly') %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Subject:</label>
            <%= text_field_tag(:'subject-text', nil, class:"form-control") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class:"form-control") %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag('Send message', class:"btn btn-primary") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="col-form-label">Recipient:</label>
            <%= text_field_tag(:'recipient-text', nil, class:"form-control", readonly:'readonly') %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Subject:</label>
            <%= text_field_tag(:'subject-text', nil, class:"form-control", required:"required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class:"form-control") %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag('Send message', class:"btn btn-primary") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/categories/_form.html.erb
<h1 class="page-header">Categorias</h1>
<div class="col-lg-12">
  <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

      <div id="error_explanation">
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= action %>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-6">
          <%= form_for ([:backoffice, @category]) do |f| %>
            <div class="form-group">
              <label>Descrição</label>
              <%= f.text_field :description, class:"form-control", placeholder:"Ex.: Petshop" %>
            </div>
              <%= f.submit "Enviar", class:"btn btn-primary" %>
              <%= link_to "Voltar", backoffice_categories_path, class:"btn btn-default" %>
          <% end %>
        </div>
        <!-- /.col-lg-6 (nested) -->
      </div>
      <!-- /.row (nested) -->
    </div>
    <!-- /.panel-body -->
  </div>
</div>

app/views/backoffice/categories/edit.html.erb
<%= render partial: 'form', locals: {action: 'Editando Cadastro'} %>

app/views/backoffice/categories/index.html.erb
<h1>Backoffice::Categories#index</h1>
<p>Find me in app/views/backoffice/categories/index.html.erb</p>

app/views/backoffice/categories/new.html.erb
<%= render partial: 'form', locals: {action: 'Novo Cadastro'} %>

app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

app/views/backoffice/send_mail/create.js.erb
$(function(){
  $('#sendMailModal').modal('hide');
  $('#subject-text').val('');
  $('#message-text').val('');

  $.notify("<%= @notify_message %>", "<%= @notify_flag %>")
});

app/views/backoffice/send_mail/edit.js.erb
$(function(){
  $('h4.modal-title').text('Mensagem para: <%= @admin.name %>');
  $('#recipient-text').val('<%= @admin.email %>');

  $('#sendMailModal').modal();

  $('#sendMailModal').on('shown.bs.modal', function () {
    $('#subject-text').trigger('focus')
  })
});

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">Escambor - Backoffice</a>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
    <li> <%= current_admin.email %> </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to destroy_admin_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i>
            Logout
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <%= link_to backoffice_dashboard_path do %>
            <i class="fa fa-dashboard fa-fw"></i> Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to backoffice_categories_path do %>
            <i class="fa fa-th-list"></i> Categorias
          <% end %>
        </li>
        <li>
          <%= link_to backoffice_admins_path do %>
            <i class="fa fa-user"></i> Administradores
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/site_shared/_footer.html.erb
<!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>